### ISSUE TITLE
Document building technology

### ISSUE THREAD

**Issue by delapuente** [aframevr-userland/aframe-cli#65]
aframe-cli projects are built using [brunch](http://brunch.io/) but this is not indicated. When starting from a template but evolving the project, it could be convenient to hack into the build process. Add a link to the Brunch homepage to explicitly highlight the building technology and provide a point of entry for those developers that want to customise the building process.

**Comment by cvan** [comment]
Thanks for filing this. This project is still evolving so thanks for being a patient guinea pig. I've already filed issue #24 for this. Will be simplifying the build system soon. In my new branch, I just added optional support for other systems.
