### ISSUE TITLE
Wrong Git URL with template

### ISSUE THREAD

**Issue by chris-aeviator** [aframevr-userland/aframe-cli#78]
When trying to use the `--template` option with a git repository

e.g. `aframe new my-360-tour --template repository/360-tour-template` the CLI tries to clone from a  different URL to the one defined

#### Output:
`Error: Git clone error: Error: Command failed: git clone git://github.com/aframe-repository/360-tour-template-template.git "/Users/korny/.brunch/skeletons/f3c13a33a16659066ddedb8c324772a51569442b"`.

It wrongly pre-pends the string **"aframe-"** and appends the string **-template**"

**Comment by cvan** [comment]
Many thanks for filing this issue! Have a [branch in a PR](https://github.com/aframevr-userland/aframe-cli/pull/68) that will be addressing this. Will update this bug when it's resolved. Thanks for using and testing 👍

**Comment by cvan** [comment]
thanks for your patience. I opened a new PR (#82) to address this bug.

the fix worked well for me. if you have a moment, could you pull it locally and ensure that it fixes your problems:

```sh
npm install 'cvan/aframe-cli#14af0f3' --save
```

appreciate the help and guinea-pigging!
